<?php

namespace Database\Seeders;

use App\Models\M_mt_ter_ptkp;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class Mt_ter_ptkpSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        M_mt_ter_ptkp::insert(
            [
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 5400000,
                    'persen' => '0',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 5650000,
                    'persen' => '0.25',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 5950000,
                    'persen' => '0.5',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 6300000,
                    'persen' => '0.75',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 6750000,
                    'persen' => '1',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 7500000,
                    'persen' => '1.25',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 8550000,
                    'persen' => '1.5',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 9650000,
                    'persen' => '1.75',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 10050000,
                    'persen' => '2',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 10350000,
                    'persen' => '2.25',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 10700000,
                    'persen' => '2.5',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 11050000,
                    'persen' => '3',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 11600000,
                    'persen' => '3.5',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 12500000,
                    'persen' => '4',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 13750000,
                    'persen' => '5',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 15100000,
                    'persen' => '6',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 16950000,
                    'persen' => '7',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 19750000,
                    'persen' => '8',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 24150000,
                    'persen' => '9',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 26450000,
                    'persen' => '10',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 28000000,
                    'persen' => '11',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 30050000,
                    'persen' => '12',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 32400000,
                    'persen' => '13',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 35400000,
                    'persen' => '14',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 39100000,
                    'persen' => '15',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 43850000,
                    'persen' => '16',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 47800000,
                    'persen' => '17',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 51400000,
                    'persen' => '18',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 56300000,
                    'persen' => '19',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 62200000,
                    'persen' => '20',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 68600000,
                    'persen' => '21',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 77500000,
                    'persen' => '22',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 89000000,
                    'persen' => '23',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 103000000,
                    'persen' => '24',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 125000000,
                    'persen' => '25',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 157000000,
                    'persen' => '26',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 206000000,
                    'persen' => '27',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 337000000,
                    'persen' => '28',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 454000000,
                    'persen' => '29',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 550000000,
                    'persen' => '30',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 695000000,
                    'persen' => '31',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 910000000,
                    'persen' => '32',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '1',
                    'nilai' => 1400000000,
                    'persen' => '33',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 6200000,
                    'persen' => '0',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 6500000,
                    'persen' => '0.25',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 6850000,
                    'persen' => '0.5',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 7300000,
                    'persen' => '0.75',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 9200000,
                    'persen' => '1',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 10750000,
                    'persen' => '1.5',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 11250000,
                    'persen' => '2',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 11600000,
                    'persen' => '2.5',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 12600000,
                    'persen' => '3',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 13600000,
                    'persen' => '4',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 14950000,
                    'persen' => '5',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 16400000,
                    'persen' => '6',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 18450000,
                    'persen' => '7',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 21850000,
                    'persen' => '8',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 26000000,
                    'persen' => '9',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 27700000,
                    'persen' => '10',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 29350000,
                    'persen' => '11',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 31450000,
                    'persen' => '12',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 33950000,
                    'persen' => '13',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 37100000,
                    'persen' => '14',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 41100000,
                    'persen' => '15',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 45800000,
                    'persen' => '16',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 49500000,
                    'persen' => '17',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 53800000,
                    'persen' => '18',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 58500000,
                    'persen' => '19',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 64000000,
                    'persen' => '20',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 71000000,
                    'persen' => '21',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 80000000,
                    'persen' => '22',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 93000000,
                    'persen' => '23',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 109000000,
                    'persen' => '24',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 129000000,
                    'persen' => '25',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 163000000,
                    'persen' => '26',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 211000000,
                    'persen' => '27',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 374000000,
                    'persen' => '28',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 459000000,
                    'persen' => '29',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 555000000,
                    'persen' => '30',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 704000000,
                    'persen' => '31',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 957000000,
                    'persen' => '32',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '2',
                    'nilai' => 1405000000,
                    'persen' => '33',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 6600000,
                    'persen' => '0',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 6950000,
                    'persen' => '0.25',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 7350000,
                    'persen' => '0.5',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 7800000,
                    'persen' => '0.75',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 8850000,
                    'persen' => '1',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 9800000,
                    'persen' => '1.25',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 10950000,
                    'persen' => '1.5',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 11200000,
                    'persen' => '1.75',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 12050000,
                    'persen' => '2',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 12950000,
                    'persen' => '3',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 14150000,
                    'persen' => '4',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 15550000,
                    'persen' => '5',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 17050000,
                    'persen' => '6',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 19500000,
                    'persen' => '7',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 22700000,
                    'persen' => '8',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 26600000,
                    'persen' => '9',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 28100000,
                    'persen' => '10',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 30100000,
                    'persen' => '11',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 32600000,
                    'persen' => '12',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 35400000,
                    'persen' => '13',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 38900000,
                    'persen' => '14',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 43000000,
                    'persen' => '15',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 47400000,
                    'persen' => '16',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 51200000,
                    'persen' => '17',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 55800000,
                    'persen' => '18',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 60400000,
                    'persen' => '19',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 66700000,
                    'persen' => '20',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 74500000,
                    'persen' => '21',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 83200000,
                    'persen' => '22',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 95600000,
                    'persen' => '23',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 110000000,
                    'persen' => '24',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 134000000,
                    'persen' => '25',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 169000000,
                    'persen' => '26',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 221000000,
                    'persen' => '27',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 390000000,
                    'persen' => '28',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 463000000,
                    'persen' => '29',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 561000000,
                    'persen' => '30',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 709000000,
                    'persen' => '31',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 965000000,
                    'persen' => '32',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 1419000000,
                    'persen' => '33',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'grup' => '3',
                    'nilai' => 1419000000,
                    'persen' => '34',
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],

            ]
        );
    }
}
