<?php

namespace Database\Seeders;

use App\Models\M_users_submenu;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class Mt_users_submenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        M_users_submenu::insert(
            [
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'Profile',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 1,
                    'url' => 'usr_profile',
                    'f_menu' => 1,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'Dashboard',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 1,
                    'url' => 'adm_dashboard',
                    'f_menu' => 6,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'Role',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 2,
                    'url' => 'adm_role',
                    'f_menu' => 6,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'Menu',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 3,
                    'url' => 'adm_menu',
                    'f_menu' => 6,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'Submenu',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 4,
                    'url' => 'adm_submenu',
                    'f_menu' => 6,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'Setting App',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 5,
                    'url' => 'adm_settingapp',
                    'f_menu' => 6,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'Absensi',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 1,
                    'url' => 'rpt_absensi',
                    'f_menu' => 4,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'Slip Gaji',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 2,
                    'url' => 'rpt_slipgaji',
                    'f_menu' => 4,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'Akuntansi',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 3,
                    'url' => 'rpt_akuntansi',
                    'f_menu' => 4,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'Master Standar',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 1,
                    'url' => 'mt_table',
                    'f_menu' => 5,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'Org',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 2,
                    'url' => 'mt_org',
                    'f_menu' => 5,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'User',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 3,
                    'url' => 'mt_user',
                    'f_menu' => 5,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'Karyawan',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 4,
                    'url' => 'mt_karyawan',
                    'f_menu' => 5,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'Divisi',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 5,
                    'url' => 'mt_divisi',
                    'f_menu' => 5,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'Jabatan',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 6,
                    'url' => 'mt_jabatan',
                    'f_menu' => 5,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'Jam Kerja & Shift',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 7,
                    'url' => 'mt_jamkerja',
                    'f_menu' => 5,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'HR Setting',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 8,
                    'url' => 'mt_hrsetting',
                    'f_menu' => 5,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'Closing',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 9,
                    'url' => 'mt_closing',
                    'f_menu' => 5,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'Payroll',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 1,
                    'url' => 'keu_payroll',
                    'f_menu' => 3,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'Payroll Additional',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 2,
                    'url' => 'keu_add',
                    'f_menu' => 3,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'Upload Absen',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 1,
                    'url' => 'hris_upload',
                    'f_menu' => 2,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'Data Absen',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 2,
                    'url' => 'hris_absensi',
                    'f_menu' => 2,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
                [
                    'uuid' => Str::uuid(),
                    'nama' => 'Absen Approval',
                    'ket' => NULL,
                    'icon' => 'tabler:point-filled',
                    'seq' => 3,
                    'url' => 'hris_approval',
                    'f_menu' => 2,
                    'f_status' => '2',
                    'f_org' => '1',
                    'create' => NULL,
                    'update' => NULL,
                ],
            ]
        );
    }
}
